import "./globals.css";
import { Figtree } from "next/font/google";

import Sidebar from "@/components/Sidebar";
import Player from "@/components/Player";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import getSongsByUserId from "@/actions/getSongsByUserId";

const font = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Spotify Clone", // Tab display name
  description: "Music service application generated by create next app",
};

export const revalidate = 0; // Prevent caching page (data will always be up-to-date)

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch all songs belongs to current user
  const userSongs = await getSongsByUserId();

  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <SupabaseProvider>
          {/* !! UserProvider must be inside SupabaseProvider */}
          <UserProvider>
            {/* Modal */}
            <ModalProvider />
            {/* Content */}
            <Sidebar songs={userSongs}>
              <main className="flex-1 h-full overflow-y-auto py-2">
                {children}
              </main>
            </Sidebar>
            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
